# Generated by Django 4.2.3 on 2023-08-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_order_address_order_phone_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order placed', 'Order placed'), ('shipped', 'shipped'), ('out for delivery', 'out for delivery'), ('Deliverd', 'Delivered'), ('cancelled', 'cancelled')], default='order placed', max_length=100),
        ),
    ]
