# Generated by Django 4.2.3 on 2023-08-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order placed', 'Order placed'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Deliverd', 'Delivered'), ('Cancelled', 'Cancelled')], default='Order placed', max_length=100),
        ),
    ]
